[build]
builder = "DOCKERFILE"
dockerfilePath = "pocketbase/Dockerfile"
watchPatterns = ["pocketbase/**", "pb_migrations/**"]

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
